windicss: config support & fixed class parsing
lumeland/experimental-plugins pull request #2
Opened 2021-12-14 06:14 UTC by dragonwocky

hey! i was trying to get windicss working in one of my projects and found a couple of things that weren't working right

`new HTMLParser() ... .join("")` needed a space to process classes separately/properly (`.join(" ")`) -- without the space e.g. if there was `<div class="flex"> <p class="text-red-500 bold"></p> </div>` it would end up being processed as `flextext-red-500 bold`

I've also added support for loading a config, e.g. for customising colours/breakpoints. it's taken as an property of the `.use()` plugin constructor, but of course it could be put in a separate file and `import`ed into your `_config.ts` to use it as per https://windicss.org/guide/configuration.html

2021-12-14 14:54 UTC, oscarotero commented
Hi @dragonwocky 
Very nice work, thank you very much!

Postcss can process the css files generated with windi, but cannot import these files in other css file. I mean, something like this wouldn't work:

```css
@import "./windi-output.css";
```

And about css per page, I don't know if it's something that is used a lot. In that case, maybe the plugin could insert the css in the html using a `<style>` tag.

2021-12-15 07:01 UTC, dragonwocky commented
alright, this should be ready to go

- windi's custom style tag language will now always result in replacement of the custom style tag with the generated css (so that inline style tags don't end up being shared unintentionally between documents).

- by setting `options.output.mode` to `"styleTag"` you can choose to append a `<style>` tag to each page instead of generating a file.

2021-12-16 11:06 UTC, oscarotero requested changes

2021-12-16 11:06 UTC, oscarotero commented on windicss/windicss.ts
> +  );
This looks a bit hacky. I think we can use the DOM api here:
```js
page.document.querySelectorAll('style[lang="windi"]').forEach((style) => ...);
```

2021-12-16 11:33 UTC, dragonwocky commented
i've made both those changes & also bumped the dependency version to v3.3.0 - it worked without any problems after testing, so we might as well be on the latest

2021-12-16 11:40 UTC, oscarotero requested changes

2021-12-16 11:40 UTC, oscarotero commented on windicss/deps.ts
> +} from "https://deno.land/x/deno_dom@v0.1.19-alpha/deno-dom-wasm.ts";
this library is included in Lume, so you could import it directly with `lume/deps/dom.ts` in windicss.ts (this ensures that we are using the same version in both places)

2021-12-16 11:43 UTC, oscarotero approved these changes

2021-12-16 11:43 UTC, merged

2021-12-16 11:43 UTC, oscarotero commented
Thank you! Fantastic work