add plugin for checking broken links
lumeland/experimental-plugins pull request #39
Opened 2024-06-25 17:11 UTC by iacore

2024-06-25 18:31 UTC, iacore commented
it works with resolve_urls
nice!

2024-06-25 21:45 UTC, oscarotero requested changes

2024-06-25 21:45 UTC, oscarotero commented on check_links/mod.ts
> +        for (const page of site.pages) {
This loop is executed for every url found in the html code. It should be moved outside this function and run only once. For example:

```js
const urls = new Set<string>(); // Set is more performant than arrays

site.process("*", (pages) => {
  url.clear(); // Clear on rebuild
  for (const page of pages) {
    urls.add(site.url(page.data.url, true)); // site.url() return the full url if the second argument is true
  }
  for (const file of site.files) {
    urls.add(site.url(file.outputPath, true));
  }
});

site.use(modifyUrls({
  // Use the urls
})
```

2024-06-26 04:44 UTC, iacore commented
should still merge modify_urls.ts into this

2024-06-26 09:18 UTC, oscarotero commented
nice! Can I merge it?

2024-06-26 20:26 UTC, iacore commented
new, new finding! Add this in document:

this plugin must be put after resolve_urls and relative_urls, or it will report false broken links. ideally, put it as the last plugin.


> nice! Can I merge it?

you can merge it now.

2024-06-26 20:40 UTC, iacore commented
more ux

this plugin is great. while muffet will turn a blind eye to `/a` -> `/a/`, this plugin will not.

it also checks if files by `site.copy` is... i guess i found another bug?


the issue is, let's say i have a file `a.md` that is referenced in `index.md` as `[a](./a.md)`.

i have resolve_urls turned on.

resolve_urls will rewrite the url to `/a/index.html` (wtf?)

2024-06-26 21:27 UTC, oscarotero commented
resolve_urls doesn't replace urls for pages that don't exist.
If you copy a.md, you should have a.md in your dest folder.

2024-06-26 21:47 UTC, merged

2024-06-26 21:53 UTC, oscarotero commented
> the issue is, let's say i have a file a.md that is referenced in index.md as [a](./a.md).

Okay, I just reproduced this issue. It's a bug, will fix it.

2024-06-26 22:01 UTC, oscarotero commented
Sorry, I merged this PR without review the code (I thought you only made my previous suggestions).
Why did you copy the code from modify_urls to this plugin?

2024-06-27 17:32 UTC, iacore commented
> Why did you copy the code from modify_urls to this plugin?

modify_urls uses `node.setAttribute` while this plugin doesn't. might be faster.

2024-06-27 17:39 UTC, oscarotero commented
Ah, okay.
If this plugin is merged in Lume repo, maybe it's a good idea to move this logic to a external function shared by both plugins to remove duplicated code.

2024-06-27 18:07 UTC, iacore commented
> Ah, okay. If this plugin is merged in Lume repo, maybe it's a good idea to move this logic to a external function shared by both plugins to remove duplicated code.

maybe you can add a comment at the top of the file for this.